### ISSUE TITLE
ATmega328P 3.3V/8Mhz

### ISSUE THREAD

**Issue by SerjPr** [stanekTM/TX_nRF24_2ch_OLED#1]
Good afternoon. Sorry for my not correct English. I want to use " ATmega328P 3.3V/8Mhz. Please tell me, is there anything in your code that depends on the processor frequency and voltage?

**Comment by stanekTM** [comment]
Hi, okay, I'm not an English-speaking person either.
The code should work fine, only the speed will be halved. I've never tried a 328P at 8Mhz. I have been using 328P/16Mhz at 3.3V for years without any problems. Please report if everything works as it should, I don't own an 8Mhz Arduino. Only report code issues here, otherwise use the discussion menu.
Regards Jiri stanekTM
